language: ruby
rvm:
- 2.4.1
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec
