language: ruby
rvm:
- 2.4.1
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.20.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec
